### PR TITLE
Video embiggening

### PR DESCRIPTION
**Pull request by acsulli**

### CODE REVIEW

**Review by christianh814 — APPROVED** [review]
The weird line-breaks are triggering me, but if Erik is okay with it so am I.

Otherwise /lgtm.

**Review by thoraxe — CHANGES_REQUESTED** [review]
You are going to hate me, but instead of applying styling to every single div, why don't we append the stylesheet to have the "video" div and then you just need `div class=videobox` or something?

**Comment by christianh814** [comment]
> You are going to hate me, but instead of applying styling to every single div, why don't we append the stylesheet to have the "video" div and then you just need `div class=videobox` or something?

+1

**Comment by acsulli** [comment]
> You are going to hate me, but instead of applying styling to every single div, why don't we append the stylesheet to have the "video" div and then you just need `div class=videobox` or something?

Nah, this makes sense.

**Review by thoraxe — APPROVED** [review]
I like the use of `extra_css`!

**Pull request merged**
