### PR TITLE
why are youtube embeds so annoying

### PR DESCRIPTION
**Pull request by phillamb168**
This is what I get for making assumptions about iframe URLs...

### CODE REVIEW

**Comment by thoraxe** [comment]
FYI you should be able to "run" mkdocs locally to serve it to test/validate yourself.

**Comment by phillamb168** [comment]
Nice tip - will give that a try next time and save you some work :)

**Comment by thoraxe** [comment]
@phillamb168 sure thing - let me know if it's good for PROD

**Comment by phillamb168** [comment]
Confirmed, looks good. Thank you!

**Comment by thoraxe** [comment]
Should be live in a few minutes.

**Pull request merged**
