### PR TITLE
Adding Couchbase cluster demo info

### PR DESCRIPTION
**Pull request by phillamb168**
Hi there,
This is for an RHPDS catalog item for a Couchbase Cluster workshop. Please let me know if you see anything missing. Thanks!

### CODE REVIEW

**Review by thoraxe — CHANGES_REQUESTED** [review]
Needs a change to `mkdocs.yml` in order to add this to the ToC.

**Comment by phillamb168** [comment]
@thoraxe how's this look?

**Comment by thoraxe** [comment]
@phillamb168 good enough. merging to dev. please review the dev site and approve or make a new PR if changes are needed.

Once you approve the dev site, we'll merge to prod.

Simply respond to this GH PR with "LGTM" or similar and we'll take care of it.

**Comment by phillamb168** [comment]
LGTM

**Comment by phillamb168** [comment]
Actually - I need to update the youtube embed. I'll do that now.

**Comment by phillamb168** [comment]
New PR: https://github.com/OpenShiftDemos/demo-guide/pull/103

**Pull request merged**
